export type DeviceBrand = { name: string; models: string[] };
export type DeviceCategory = {
  icon: string;
  brands: DeviceBrand[];
  colors: string[];
  open?: boolean;
};

const brand = (name: string, models: string[]): DeviceBrand => ({
  name,
  models,
});
const phoneColors = [
  "Preto",
  "Branco",
  "Azul",
  "Verde",
  "Rosa",
  "Roxo",
  "Vermelho",
  "Dourado",
  "Prata",
  "Cinza",
  "Outra",
];
const notebookColors = [
  "Preto",
  "Prata",
  "Cinza",
  "Branco",
  "Azul",
  "Dourado",
  "Outra",
];
const headphoneColors = [
  "Preto",
  "Branco",
  "Azul",
  "Rosa",
  "Vermelho",
  "Roxo",
  "Verde",
  "Outra",
];
const generalColors = [
  "Preto",
  "Branco",
  "Azul",
  "Cinza",
  "Prata",
  "Vermelho",
  "Outra",
];

export const equipmentCategories: Record<string, DeviceCategory> = {
  Celular: {
    icon: "phone",
    colors: phoneColors,
    brands: [
      brand("Apple", [
        "iPhone 11",
        "iPhone 11 Pro",
        "iPhone 11 Pro Max",
        "iPhone 12",
        "iPhone 12 Mini",
        "iPhone 12 Pro",
        "iPhone 12 Pro Max",
        "iPhone 13",
        "iPhone 13 Mini",
        "iPhone 13 Pro",
        "iPhone 13 Pro Max",
        "iPhone 14",
        "iPhone 14 Plus",
        "iPhone 14 Pro",
        "iPhone 14 Pro Max",
        "iPhone 15",
        "iPhone 15 Plus",
        "iPhone 15 Pro",
        "iPhone 15 Pro Max",
        "iPhone 16",
        "iPhone 16 Plus",
        "iPhone 16 Pro",
        "iPhone 16 Pro Max",
      ]),
      brand("Samsung", [
        "Galaxy S20",
        "Galaxy S21",
        "Galaxy S22",
        "Galaxy S23",
        "Galaxy S24",
        "Galaxy S25",
        "Galaxy A12",
        "Galaxy A13",
        "Galaxy A14",
        "Galaxy A15",
        "Galaxy A16",
        "Galaxy A23",
        "Galaxy A24",
        "Galaxy A25",
        "Galaxy A34",
        "Galaxy A35",
        "Galaxy A54",
        "Galaxy A55",
        "Galaxy Z Flip 5",
        "Galaxy Z Flip 6",
        "Galaxy Z Fold 5",
        "Galaxy Z Fold 6",
      ]),
      brand("Motorola", [
        "Moto G22",
        "Moto G23",
        "Moto G24",
        "Moto G32",
        "Moto G34",
        "Moto G54",
        "Moto G55",
        "Moto G75",
        "Moto G84",
        "Moto G85",
        "Moto E13",
        "Moto E14",
        "Edge 30",
        "Edge 40",
        "Edge 50",
        "Razr 40",
        "Razr 50",
      ]),
      brand("Xiaomi", [
        "Redmi Note 10",
        "Redmi Note 11",
        "Redmi Note 12",
        "Redmi Note 13",
        "Redmi Note 14",
        "Redmi 12",
        "Redmi 13",
        "Xiaomi 12",
        "Xiaomi 13",
        "Xiaomi 14",
        "Xiaomi 15",
        "Poco X3",
        "Poco X5",
        "Poco X6",
        "Poco F5",
        "Poco F6",
      ]),
      brand("Realme", [
        "Realme C33",
        "Realme C53",
        "Realme C55",
        "Realme C61",
        "Realme C67",
        "Realme 10",
        "Realme 11",
        "Realme 12",
        "Realme GT 5",
        "Realme GT 6",
      ]),
      brand("ASUS", [
        "Zenfone 8",
        "Zenfone 9",
        "Zenfone 10",
        "ROG Phone 5",
        "ROG Phone 6",
        "ROG Phone 7",
        "ROG Phone 8",
      ]),
      brand("Google", [
        "Pixel 6",
        "Pixel 6 Pro",
        "Pixel 7",
        "Pixel 7 Pro",
        "Pixel 8",
        "Pixel 8 Pro",
        "Pixel 9",
        "Pixel 9 Pro",
      ]),
      brand("Huawei", [
        "P30",
        "P40",
        "P50",
        "P60",
        "Mate 30",
        "Mate 40",
        "Mate 50",
        "Nova 9",
        "Nova 11",
      ]),
    ],
  },
  Notebook: {
    icon: "notebook",
    colors: notebookColors,
    brands: [
      brand("Acer", [
        "Aspire 3",
        "Aspire 5",
        "Aspire 7",
        "Nitro 5",
        "Nitro V",
        "Predator Helios",
        "Swift 3",
        "Swift Go",
      ]),
      brand("ASUS", [
        "VivoBook 15",
        "VivoBook Go",
        "ZenBook 14",
        "TUF Gaming F15",
        "TUF Gaming A15",
        "ROG Strix G15",
        "ROG Zephyrus",
      ]),
      brand("Apple", [
        "MacBook Air 2018",
        "MacBook Air 2019",
        "MacBook Air M1",
        "MacBook Air M2",
        "MacBook Air M3",
        "MacBook Pro 13",
        "MacBook Pro 14",
        "MacBook Pro 16",
      ]),
      brand("Dell", [
        "Inspiron 15 3000",
        "Inspiron 15 3520",
        "Inspiron 14",
        "Vostro 15",
        "Latitude 3420",
        "Latitude 3520",
        "G15",
        "XPS 13",
        "XPS 15",
      ]),
      brand("Lenovo", [
        "IdeaPad 1",
        "IdeaPad 3",
        "IdeaPad Gaming 3",
        "ThinkPad E14",
        "ThinkPad E15",
        "ThinkPad T14",
        "Legion 5",
        "LOQ",
        "Yoga",
      ]),
      brand("Samsung", [
        "Galaxy Book",
        "Galaxy Book2",
        "Galaxy Book3",
        "Galaxy Book4",
        "Book Go",
        "Odyssey",
      ]),
      brand("HP", [
        "HP 240",
        "HP 246",
        "HP 250",
        "Pavilion",
        "ProBook",
        "EliteBook",
        "Victus",
        "Omen",
      ]),
      brand("Positivo", ["Motion", "Vision", "Master", "Stilo"]),
      brand("Avell", ["A52", "A62", "B.On", "Storm", "Mob"]),
      brand("VAIO", ["FE14", "FE15", "Fit 15S", "SX14", "Z"]),
      brand("Multilaser", ["Legacy", "Ultra", "M-Pro"]),
    ],
  },
  "Fone de ouvido": {
    icon: "headphones",
    colors: headphoneColors,
    brands: [
      brand("Apple", [
        "AirPods 1",
        "AirPods 2",
        "AirPods 3",
        "AirPods 4",
        "AirPods Pro",
        "AirPods Pro 2",
        "AirPods Max",
      ]),
      brand("Samsung", [
        "Galaxy Buds",
        "Galaxy Buds+",
        "Galaxy Buds Live",
        "Galaxy Buds Pro",
        "Galaxy Buds2",
        "Galaxy Buds2 Pro",
        "Galaxy Buds3",
        "Galaxy Buds3 Pro",
      ]),
      brand("JBL", [
        "Tune 510BT",
        "Tune 520BT",
        "Tune 710BT",
        "Tune 720BT",
        "Wave Buds",
        "Wave Beam",
        "Endurance",
        "Quantum",
      ]),
      brand("Edifier", ["W600BT", "W800BT", "W820NB", "X3", "X5", "TWS1 Pro"]),
      brand("Sony", [
        "WH-1000XM4",
        "WH-1000XM5",
        "WF-1000XM4",
        "WF-1000XM5",
        "WH-CH520",
        "WH-CH720N",
      ]),
      brand("Philips", ["TAT1108", "TAT1209", "TAH1108", "TAH4205"]),
      brand("Xiaomi", [
        "Redmi Buds 3",
        "Redmi Buds 4",
        "Redmi Buds 5",
        "Buds 3T Pro",
      ]),
      brand("QCY", ["T13", "T13 ANC", "T20", "T27", "H3", "H4"]),
      brand("Haylou", ["GT1", "GT5", "W1", "X1", "S35"]),
      brand("Beats", [
        "Studio Buds",
        "Studio Buds+",
        "Fit Pro",
        "Solo 3",
        "Solo 4",
        "Studio Pro",
      ]),
      brand("Logitech", ["G435", "G733", "G935", "Zone Vibe", "H390"]),
      brand("HyperX", [
        "Cloud II",
        "Cloud III",
        "Cloud Alpha",
        "Cloud Stinger",
        "Cloud Flight",
      ]),
      brand("Redragon", ["Zeus", "Minos", "Lamia", "Pandora"]),
    ],
  },
  Tablet: {
    icon: "tablet",
    colors: phoneColors,
    brands: [
      brand("Apple", [
        "iPad",
        "iPad 9ª geração",
        "iPad 10ª geração",
        "iPad Air",
        "iPad Air 11",
        "iPad Air 13",
        "iPad Mini",
        "iPad Pro 11",
        "iPad Pro 12.9",
        "iPad Pro 13",
      ]),
      brand("Samsung", [
        "Galaxy Tab A",
        "Galaxy Tab A7",
        "Galaxy Tab A8",
        "Galaxy Tab A9",
        "Galaxy Tab S6",
        "Galaxy Tab S7",
        "Galaxy Tab S8",
        "Galaxy Tab S9",
        "Galaxy Tab S10",
        "Galaxy Tab Active",
      ]),
      brand("Xiaomi", [
        "Redmi Pad",
        "Redmi Pad SE",
        "Xiaomi Pad 5",
        "Xiaomi Pad 6",
        "Xiaomi Pad 7",
      ]),
      brand("Lenovo", [
        "Tab M8",
        "Tab M9",
        "Tab M10",
        "Tab M11",
        "Tab P11",
        "Tab P12",
      ]),
      brand("Multilaser", ["M8", "M9", "M10", "Kid Pad"]),
      brand("Positivo", ["Vision TAB", "Twist Tab", "Q10"]),
    ],
  },
  Computador: {
    icon: "computer",
    colors: generalColors,
    brands: [
      brand("Dell", ["OptiPlex", "Vostro Desktop", "Precision"]),
      brand("HP", ["ProDesk", "EliteDesk", "Pavilion Desktop"]),
      brand("Lenovo", ["ThinkCentre", "IdeaCentre", "Legion Tower"]),
      brand("Positivo", ["Master", "Union"]),
      brand("Apple", ["iMac", "Mac mini", "Mac Studio", "Mac Pro"]),
      brand("ASUS", ["ExpertCenter", "ROG Desktop"]),
    ],
  },
  Console: {
    icon: "console",
    colors: generalColors,
    brands: [
      brand("Sony", [
        "PlayStation 3",
        "PlayStation 4",
        "PlayStation 4 Pro",
        "PlayStation 5",
        "PlayStation 5 Slim",
      ]),
      brand("Microsoft", [
        "Xbox 360",
        "Xbox One",
        "Xbox One S",
        "Xbox One X",
        "Xbox Series S",
        "Xbox Series X",
      ]),
      brand("Nintendo", [
        "Nintendo Switch",
        "Nintendo Switch Lite",
        "Nintendo Switch OLED",
      ]),
    ],
  },
  TV: {
    icon: "tv",
    colors: generalColors,
    brands: [
      brand("Samsung", ["Crystal UHD", "QLED", "Neo QLED", "The Frame"]),
      brand("LG", ["UHD", "NanoCell", "OLED", "QNED"]),
      brand("Philips", ["Smart TV", "The One", "Ambilight"]),
      brand("TCL", ["P635", "P755", "C645", "C755"]),
      brand("AOC", ["Roku TV", "Smart TV"]),
      brand("Sony", ["Bravia", "Bravia OLED"]),
    ],
  },
  Monitor: {
    icon: "monitor",
    colors: generalColors,
    brands: [
      brand("AOC", ["Hero", "Speed", "Agon"]),
      brand("LG", ["UltraGear", "UltraWide", "MyView"]),
      brand("Samsung", ["Odyssey", "ViewFinity", "Essential"]),
      brand("Dell", ["P Series", "S Series", "UltraSharp"]),
      brand("Acer", ["Nitro", "Predator", "Vero"]),
    ],
  },
  Impressora: {
    icon: "printer",
    colors: generalColors,
    brands: [
      brand("Epson", [
        "EcoTank L3250",
        "EcoTank L4260",
        "EcoTank L5290",
        "WorkForce",
      ]),
      brand("HP", ["DeskJet", "Ink Tank", "Smart Tank", "LaserJet"]),
      brand("Canon", ["PIXMA", "Mega Tank", "imageCLASS"]),
      brand("Brother", ["DCP", "HL", "MFC"]),
      brand("Samsung", ["Xpress", "ProXpress"]),
    ],
  },
  Smartwatch: {
    icon: "watch",
    colors: phoneColors,
    brands: [
      brand("Apple", [
        "Apple Watch SE",
        "Apple Watch Series 7",
        "Apple Watch Series 8",
        "Apple Watch Series 9",
        "Apple Watch Series 10",
        "Apple Watch Ultra",
      ]),
      brand("Samsung", [
        "Galaxy Watch4",
        "Galaxy Watch5",
        "Galaxy Watch6",
        "Galaxy Watch7",
        "Galaxy Watch Ultra",
      ]),
      brand("Xiaomi", ["Mi Watch", "Redmi Watch", "Smart Band"]),
      brand("Garmin", ["Forerunner", "Fenix", "Venu"]),
      brand("Huawei", ["Watch GT", "Watch Fit"]),
      brand("Amazfit", ["Bip", "GTS", "GTR", "T-Rex"]),
    ],
  },
  Acessório: {
    icon: "other",
    colors: generalColors,
    brands: [
      brand("Apple", [
        "Magic Mouse",
        "Magic Keyboard",
        "Apple Pencil",
        "MagSafe",
      ]),
      brand("Samsung", ["S Pen", "DeX", "Carregador"]),
      brand("Logitech", ["Mouse", "Teclado", "Webcam", "Controle"]),
      brand("JBL", ["Caixa de som", "Microfone"]),
    ],
  },
  Eletrônico: { icon: "other", colors: generalColors, brands: [] },
  Outro: { icon: "other", colors: [], brands: [], open: true },
};

export const equipmentCategoryNames = Object.keys(equipmentCategories);
export const publicDeviceCategories = [
  "Fone de ouvido",
  "Celular",
  "Notebook",
  "Tablet",
  "Outro",
].map((name) => ({ name, icon: equipmentCategories[name].icon }));
export const colorSwatches: Record<string, string> = {
  Preto: "#111820",
  Branco: "#f4f5f5",
  Azul: "#315f85",
  Vermelho: "#a83d3d",
  Verde: "#557968",
  Cinza: "#727b80",
  Dourado: "#b69a62",
  Prata: "#b8bec1",
  Rosa: "#c98e9b",
  Roxo: "#756184",
  Outra: "linear-gradient(135deg,#06141B 0 33%,#9BA8AB 33% 66%,#CCD0CF 66%)",
};
export function getEquipmentCategory(category: string) {
  return equipmentCategories[category] || equipmentCategories.Outro;
}
